### PR TITLE
Show/Hide job queue according to privacy setting

### LINKED ISSUE #40: [Suggestion] Toggle to enable/disable printed jobs history
Hi.  

I think it should be possible to disable the printed history on the printer options.  

Maybe implement it on the privacy settings?

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #40 

Also moves construction code into `construct {}` clause and uses Object-style creation.

### CODE REVIEW

**Review by danrabbit — COMMENTED** [review]
Hm I don't have a printer to test, but reading through this seems like kind of a false privacy. I don't think the issue is whether the queue is shown while privacy mode is enabled, but whether jobs are saved in the queue after they're printed. Correct me if I'm wrong here, but wouldn't all the previous jobs show in the queue again if someone were to go change the remember files setting?

I think a case for privacy here is for example you're working on a shared computer and you go turn on privacy mode, print something sensitive, and then turn privacy mode back off so that there's no record of you having made that print.

Or perhaps you just leave privacy mode on all the time, but if someone where to use the computer and turn privacy mode off, you'd want to make sure that this means the print history queue is still empty and not that the queue is now revealed.

**Comment by jeremypw** [comment]
@danrabbit Good point.  I'll look into whether it is possible to clear the queue at the system level as well (and not save new jobs to it) when privacy is on.

**Comment by jeremypw** [comment]
There is a "Clear History" button in the Privacy settings but not sure whether this clears the job queue. I'll check.

**Comment by jeremypw** [comment]
"Clear History" in the Privacy plug does not clear the printer queue. I have raised on issue regarding this.  I have also pushed a PR for a button that clears the queue.

**Comment by jeremypw** [comment]
If the Privacy plug offers the ability to clear the printer queue then maybe this PR will not be needed.

**Comment by jeremypw** [comment]
CLosing as outdated.  Maybe better implemented in the privacy plug anyway.

**Pull request closed without merging**
