### PR TITLE
Fix ink level style classes

### PR DESCRIPTION
**Pull request by danrabbit**
Doesn't fix an issue where ink levels don't seem to show up. I had to manually change the level in inspector

### CODE REVIEW

**Comment by jeremypw** [comment]
Needs someone with a suitable colour printer to test this.

**Comment by cassidyjames** [comment]
I don't have a color printer set up with elementary OS at the moment, but can see if I can get @katiemkblaede's printer to cooperate.

**Comment by cassidyjames** [comment]
I've been unable to confirm that this changes anything for me. There were still four big blank buttons instead of any color. But that might be a different issue, so I'll need to investigate more (and maybe drag the printer over to plug it in with USB instead of relying on its finicky network configuration).

**Comment by danrabbit** [comment]
@cassidyjames Like I mentioned in the description, there's some other issue somewhere that the levels aren't actually being set. So you have to manually set levels in inspector. This just fixes the style classes themselves so it's half of the problem

**Comment by cassidyjames** [comment]
@danrabbit ah, I didn't quite understand that before. Gotcha. :smile: I'll take another look.

**Pull request merged**
