### PR TITLE
Release 2.2.0

### PR DESCRIPTION
**Pull request by jeremypw**
* Bump version in meson.build and appdata

TODO

* [x] Update screenshot to show new UX
* [ ] Update appdata for any new merges

PRs that would be nice to merge before this release: #168 and #169 (and possibly #163)

### CODE REVIEW

**Comment by jeremypw** [comment]
@danrabbit Do you fancy providing some new screenshots (when the last PR for this release has been merged)? I do not have a color printer so cannot easily show realistically changes to the ink-level view.  Also be nice to show changes to the job queue appearance and add printer dialog.

**Comment by danrabbit** [comment]
I don't have a printer either haha so for the ink level PR I actually faked the data 😅 It might be easier to find someone who has a printer to show off the queue changes

**Comment by jeremypw** [comment]
OK. I have a monochrome laser printer. I guess I could fake data for the ink-level view - I'll see what I can do.

**Review by danrabbit — APPROVED** [review]
Whenever you're ready @jeremypw! Great work :tada:

**Pull request merged**
