### PR TITLE
Fix DbusNotifier and state printer

### LINKED ISSUE #90: Switch status does not change status in printer list.
Toggling the switch in the printer page does not change the appearance and message for the printer in the printer list.  NB The printer in question is attached to a local server and the issue occurs on a client.  Printing to the printer from e.g. Chromium on the client was successful.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/57555768-switch-status-does-not-change-status-in-printer-list?utm_campaign=plugin&utm_content=tracker%2F60188248&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F60188248&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by torikulhabib**
Fixes #90 

when a property is found it will also register the object

### CODE REVIEW

**Comment by jeremypw** [comment]
Are there known issues that this will fix/improve?

**Comment by torikulhabib** [comment]
Signal from dbus notifier not really working method before.
this method dbus signal working.

**Comment by jeremypw** [comment]
OK, thank you for the PR and for working on this plug.  If there are any of the issues reported at https://github.com/elementary/switchboard-plug-printers/issues that could be caused by the dbus signal not working it would be good to link them to this PR. Just put "Fixes #<issue number>" in the description.  It would help reviewers prioritize and test the PR.

**Comment by torikulhabib** [comment]
this linked with this issue...
https://github.com/elementary/switchboard-plug-printers/issues/90

**Review by jeremypw — CHANGES_REQUESTED** [review]
After a reboot, this worked for a local printer entry (even though the printer was not plugged in to the computer) but did not work for a remote printer entry (even though the printer was available as indicated by the list shown when the "+" button was clicked.

When trying to toggle the switch from "disabled" to "enabled" for the remote printer, the switch immediately reverted to the "disabled" position.

**Comment by danrabbit** [comment]
Looks like the linked issues were resolved by #168

**Pull request closed without merging**
